

const preA1Vocabulary = [
  // Colors
  { en: 'black', ru: 'черный' }, // [cite: 3]
  { en: 'blue', ru: 'синий / голубой' }, // [cite: 4]
  { en: 'brown', ru: 'коричневый' }, // [cite: 5]
  { en: 'color', ru: 'цвет' }, // [cite: 6]
  { en: 'green', ru: 'зеленый' }, // [cite: 7]
  { en: 'gray', ru: 'серый' }, // [cite: 8]
  { en: 'orange', ru: 'оранжевый' }, // [cite: 9]
  { en: 'pink', ru: 'розовый' }, // [cite: 10]
  { en: 'purple', ru: 'фиолетовый' }, // [cite: 11]
  { en: 'red', ru: 'красный' }, // [cite: 12]
  { en: 'white', ru: 'белый' }, // [cite: 13]
  { en: 'yellow', ru: 'желтый' }, // [cite: 14]

  // Family & friends
  { en: 'baby', ru: 'малыш' }, // [cite: 16]
  { en: 'boy', ru: 'мальчик' }, // [cite: 17]
  { en: 'brother', ru: 'брат' }, // [cite: 18]
  { en: 'child / children', ru: 'ребенок / дети' }, // [cite: 19]
  { en: 'cousin', ru: 'двоюродный брат / сестра' }, // [cite: 20]
  { en: 'dad (daddy)', ru: 'папа' }, // [cite: 21]
  { en: 'family', ru: 'семья' }, // [cite: 22]
  { en: 'father', ru: 'отец' }, // [cite: 23]
  { en: 'friend', ru: 'друг' }, // [cite: 24]
  { en: 'girl', ru: 'девочка' }, // [cite: 25]
  { en: 'grandfather', ru: 'дедушка' }, // [cite: 26]
  { en: 'grandma', ru: 'бабуля' }, // [cite: 27]
  { en: 'grandmother', ru: 'бабушка' }, // [cite: 28]
  { en: 'grandpa', ru: 'дедуля' }, // [cite: 29]
  { en: 'live', ru: 'жить' }, // [cite: 30]
  { en: 'man / men', ru: 'мужчина / мужчины' }, // [cite: 31]
  { en: 'mother', ru: 'мать' }, // [cite: 32]
  { en: 'mum (mummy)', ru: 'мама' }, // [cite: 33]
  { en: 'old', ru: 'старый' }, // [cite: 34]
  { en: 'person / people', ru: 'человек / люди' }, // [cite: 35]
  { en: 'sister', ru: 'сестра' }, // [cite: 36]
  { en: 'woman / women', ru: 'женщина / женщины' }, // [cite: 37]
  { en: 'young', ru: 'молодой' }, // [cite: 38]

  // Food & drink
  { en: 'apple', ru: 'яблоко' }, // [cite: 40]
  { en: 'banana', ru: 'банан' }, // [cite: 41]
  { en: 'bean', ru: 'фасоль / боб' }, // [cite: 42]
  { en: 'bread', ru: 'хлеб' }, // [cite: 43]
  { en: 'breakfast', ru: 'завтрак' }, // [cite: 44]
  { en: 'burger', ru: 'бургер' }, // [cite: 45]
  { en: 'cake', ru: 'торт / пирожное' }, // [cite: 46]
  { en: 'carrot', ru: 'морковь' }, // [cite: 47]
  { en: 'chicken', ru: 'курица' }, // [cite: 48]
  { en: 'chips', ru: 'чипсы / картофель фри' }, // [cite: 49]
  { en: 'coconut', ru: 'кокос' }, // [cite: 50]
  { en: 'dinner', ru: 'ужин' }, // [cite: 51]
  { en: 'drink', ru: 'напиток / пить' }, // [cite: 52]
  { en: 'eat', ru: 'есть (кушать)' }, // [cite: 53]
  { en: 'egg', ru: 'яйцо' }, // [cite: 54]
  { en: 'fish', ru: 'рыба' }, // [cite: 55]
  { en: 'food', ru: 'еда' }, // [cite: 56]
  { en: 'fruit', ru: 'фрукты' }, // [cite: 57]
  { en: 'grape', ru: 'виноград' }, // [cite: 58]
  { en: 'ice cream', ru: 'мороженое' }, // [cite: 59]
  { en: 'juice', ru: 'сок' }, // [cite: 60]
  { en: 'lemon', ru: 'лимон' }, // [cite: 61]
  { en: 'lemonade', ru: 'лимонад' }, // [cite: 62]
  { en: 'lime', ru: 'лайм' }, // [cite: 63]
  { en: 'lunch', ru: 'обед' }, // [cite: 64]
  { en: 'mango', ru: 'манго' }, // [cite: 65]
  { en: 'meat', ru: 'мясо' }, // [cite: 66]
  { en: 'milk', ru: 'молоко' }, // [cite: 67]
  { en: 'onion', ru: 'лук' }, // [cite: 68]
  { en: 'orange', ru: 'апельсин' }, // [cite: 69]
  { en: 'pea', ru: 'горох' }, // [cite: 70]
  { en: 'pear', ru: 'груша' }, // [cite: 71]
  { en: 'pineapple', ru: 'ананас' }, // [cite: 72]
  { en: 'potato', ru: 'картофель' }, // [cite: 73]
  { en: 'rice', ru: 'рис' }, // [cite: 74]
  { en: 'sausage', ru: 'сосиска' }, // [cite: 75]
  { en: 'supper', ru: 'поздний ужин' }, // [cite: 76]
  { en: 'tomato', ru: 'помидор' }, // [cite: 77]
  { en: 'water', ru: 'вода' }, // [cite: 78]
  { en: 'watermelon', ru: 'арбуз' }, // [cite: 79]

  // Home
  { en: 'apartment (flat)', ru: 'квартира' }, // [cite: 81]
  { en: 'armchair', ru: 'кресло' }, // [cite: 82]
  { en: 'bath', ru: 'ванна' }, // [cite: 83]
  { en: 'bathroom', ru: 'ванная комната' }, // [cite: 84]
  { en: 'bed', ru: 'кровать' }, // [cite: 85]
  { en: 'bedroom', ru: 'спальня' }, // [cite: 86]
  { en: 'bookcase', ru: 'книжный шкаф' }, // [cite: 87]
  { en: 'box', ru: 'коробка' }, // [cite: 88]
  { en: 'camera', ru: 'камера / фотоаппарат' }, // [cite: 89]
  { en: 'chair', ru: 'стул' }, // [cite: 90]
  { en: 'clock', ru: 'часы (настенные)' }, // [cite: 91]
  { en: 'computer', ru: 'компьютер' }, // [cite: 92]
  { en: 'cupboard', ru: 'шкафчик / буфет' }, // [cite: 93]
  { en: 'desk', ru: 'письменный стол' }, // [cite: 94]
  { en: 'dining room', ru: 'столовая' }, // [cite: 95]
  { en: 'doll', ru: 'кукла' }, // [cite: 96]
  { en: 'door', ru: 'дверь' }, // [cite: 97]
  { en: 'flower', ru: 'цветок' }, // [cite: 98]
  { en: 'garden', ru: 'сад' }, // [cite: 99]
  { en: 'hall', ru: 'коридор / прихожая' }, // [cite: 100]
  { en: 'house', ru: 'дом' }, // [cite: 101]
  { en: 'kitchen', ru: 'кухня' }, // [cite: 102]
  { en: 'lamp', ru: 'лампа' }, // [cite: 103]
  { en: 'livingroom', ru: 'гостиная' }, // [cite: 104]
  { en: 'mat', ru: 'коврик' }, // [cite: 105]
  { en: 'mirror', ru: 'зеркало' }, // [cite: 106]
  { en: 'painting', ru: 'картина' }, // [cite: 107]
  { en: 'phone', ru: 'телефон' }, // [cite: 108]
  { en: 'picture', ru: 'картинка' }, // [cite: 109]
  { en: 'radio', ru: 'радио' }, // [cite: 110]
  { en: 'room', ru: 'комната' }, // [cite: 111]
  { en: 'sleep', ru: 'спать' }, // [cite: 112]
  { en: 'sofa', ru: 'диван' }, // [cite: 113]
  { en: 'table', ru: 'стол' }, // [cite: 114]
  { en: 'television / TV', ru: 'телевизор' }, // [cite: 115]
  { en: 'toy', ru: 'игрушка' }, // [cite: 116]
  { en: 'tree', ru: 'дерево' }, // [cite: 117]
  { en: 'wall', ru: 'стена' }, // [cite: 118]
  { en: 'watch', ru: 'наручные часы' }, // [cite: 119]
  { en: 'window', ru: 'окно' }, // [cite: 120]

  // The world around us
  { en: 'beach', ru: 'пляж' }, // [cite: 122]
  { en: 'sand', ru: 'песок' }, // [cite: 123]
  { en: 'sea', ru: 'море' }, // [cite: 124]
  { en: 'shell', ru: 'ракушка' }, // [cite: 125]
  { en: 'street', ru: 'улица' }, // [cite: 126]
  { en: 'sun', ru: 'солнце' }, // [cite: 127]
  { en: 'tree', ru: 'дерево' }, // [cite: 128]
  { en: 'water', ru: 'вода' }, // [cite: 129]

  // Places & directions
  { en: 'behind', ru: 'позади' }, // [cite: 131]
  { en: 'between', ru: 'между' }, // [cite: 132]
  { en: 'here', ru: 'здесь' }, // [cite: 133]
  { en: 'in', ru: 'в' }, //
  { en: 'in front of', ru: 'перед' }, // [cite: 135]
  { en: 'next to', ru: 'рядом с' }, // [cite: 136]
  { en: 'on', ru: 'на' }, // [cite: 137]
  { en: 'park', ru: 'парк' }, // [cite: 138]
  { en: 'playground', ru: 'игровая площадка' }, // [cite: 139]
  { en: 'shop (store)', ru: 'магазин' }, // [cite: 140]
  { en: 'street', ru: 'улица' }, // [cite: 141]
  { en: 'there', ru: 'там' }, // [cite: 142]
  { en: 'under', ru: 'под' }, // [cite: 143]
  { en: 'ZOO', ru: 'зоопарк' }, // [cite: 144]

  // School
  { en: 'alphabet', ru: 'алфавит' }, // [cite: 146]
  { en: 'answer', ru: 'ответ / отвечать' }, // [cite: 147]
  { en: 'ask', ru: 'спрашивать' }, // [cite: 148]
  { en: 'board', ru: 'доска' }, // [cite: 149]
  { en: 'book', ru: 'книга' }, // [cite: 150]
  { en: 'bookcase', ru: 'книжный шкаф' }, // [cite: 151]
  { en: 'class', ru: 'класс / урок' }, // [cite: 152]
  { en: 'classroom', ru: 'классная комната' }, // [cite: 153]
  { en: 'close', ru: 'закрывать' }, // [cite: 154]
  { en: 'computer', ru: 'компьютер' }, // [cite: 155]
  { en: 'correct', ru: 'правильный / исправлять' }, // [cite: 156]
  { en: 'cross', ru: 'крестик / пересекать' }, // [cite: 157]
  { en: 'cupboard', ru: 'шкафчик' }, // [cite: 158]
  { en: 'desk', ru: 'парта / стол' }, // [cite: 159]
  { en: 'draw', ru: 'рисовать' }, // [cite: 160]
  { en: 'English', ru: 'английский' }, // [cite: 161]
  { en: 'eraser (rubber)', ru: 'ластик' }, // [cite: 162]
  { en: 'example', ru: 'пример' }, // [cite: 163]
  { en: 'floor', ru: 'пол / этаж' }, // [cite: 164]
  { en: 'find', ru: 'находить' }, // [cite: 165]
  { en: 'know', ru: 'знать' }, // [cite: 166]
  { en: 'learn', ru: 'учить / изучать' }, // [cite: 167]
  { en: 'lesson', ru: 'урок' }, // [cite: 168]
  { en: 'letter', ru: 'буква' }, // [cite: 169]
  { en: 'line', ru: 'линия / очередь' }, // [cite: 170]
  { en: 'listen', ru: 'слушать' }, // [cite: 171]
  { en: 'look', ru: 'смотреть' }, // [cite: 172]
  { en: 'number', ru: 'номер / число' }, // [cite: 173]
  { en: 'open', ru: 'открывать' }, // [cite: 174]
  { en: 'page', ru: 'страница' }, // [cite: 175]
  { en: 'part', ru: 'часть' }, // [cite: 176]
  { en: 'pen', ru: 'ручка' }, // [cite: 177]
  { en: 'pencil', ru: 'карандаш' }, // [cite: 178]
  { en: 'picture', ru: 'картинка' }, // [cite: 179]
  { en: 'playground', ru: 'игровая площадка' }, // [cite: 180]
  { en: 'question', ru: 'вопрос' }, // [cite: 181]
  { en: 'read', ru: 'читать' }, // [cite: 182]
  { en: 'right', ru: 'правильный / направо' }, // [cite: 183]
  { en: 'ruler', ru: 'линейка' }, // [cite: 184]
  { en: 'school', ru: 'школа' }, // [cite: 185]
  { en: 'sentence', ru: 'предложение' }, // [cite: 186]
  { en: 'sit down', ru: 'садиться' }, // [cite: 187]
  { en: 'spell', ru: 'произносить по буквам' }, // [cite: 188]
  { en: 'stand up', ru: 'вставать' }, // [cite: 189]
  { en: 'story', ru: 'история / рассказ' }, // [cite: 190]
  { en: 'teacher', ru: 'учитель' }, // [cite: 191]
  { en: 'tell', ru: 'рассказывать' }, // [cite: 192]
  { en: 'test', ru: 'тест / контрольная' }, // [cite: 193]
  { en: 'tick', ru: 'галочка / отмечать' }, // [cite: 194]
  { en: 'understand', ru: 'понимать' }, // [cite: 195]
  { en: 'wall', ru: 'стена' }, // [cite: 196]
  { en: 'window', ru: 'окно' }, // [cite: 197]
  { en: 'word', ru: 'слово' }, // [cite: 198]
  { en: 'write', ru: 'писать' }, // [cite: 199]

  // Sports & leisure
  { en: 'badminton', ru: 'бадминтон' }, // [cite: 201]
  { en: 'ball', ru: 'мяч' }, // [cite: 202]
  { en: 'baseball', ru: 'бейсбол' }, // [cite: 203]
  { en: 'basketball', ru: 'баскетбол' }, // [cite: 204]
  { en: 'beach', ru: 'пляж' }, // [cite: 205]
  { en: 'bike', ru: 'велосипед' }, // [cite: 206]
  { en: 'boat', ru: 'лодка' }, // [cite: 207]
  { en: 'book', ru: 'книга' }, // [cite: 208]
  { en: 'bounce', ru: 'отскакивать / чеканить' }, // [cite: 209]
  { en: 'camera', ru: 'камера / фотоаппарат' }, // [cite: 210]
  { en: 'catch', ru: 'ловить' }, // [cite: 211]
  { en: 'doll', ru: 'кукла' }, // [cite: 212]
  { en: 'drawing', ru: 'рисование / рисунок' }, // [cite: 213]
  { en: 'drive', ru: 'водить' }, // [cite: 214]
  { en: 'enjoy', ru: 'наслаждаться' }, // [cite: 215]
  { en: 'favourite', ru: 'любимый' }, // [cite: 216]
  { en: 'fishing', ru: 'рыбалка' }, // [cite: 217]
  { en: 'fly', ru: 'летать' }, // [cite: 218]
  { en: 'football', ru: 'футбол' }, // [cite: 219]
  { en: 'game', ru: 'игра' }, // [cite: 220]
  { en: 'guitar', ru: 'гитара' }, // [cite: 221]
  { en: 'hit', ru: 'ударять' }, // [cite: 222]
  { en: 'hobby', ru: 'хобби' }, // [cite: 223]
  { en: 'hockey', ru: 'хоккей' }, // [cite: 224]
  { en: 'jump', ru: 'прыгать' }, // [cite: 225]
  { en: 'kick', ru: 'пинать' }, // [cite: 226]
  { en: 'kite', ru: 'воздушный змей' }, // [cite: 227]
  { en: 'listen', ru: 'слушать' }, // [cite: 228]
  { en: 'painting', ru: 'живопись / рисование' }, // [cite: 229]
  { en: 'photo', ru: 'фото' }, // [cite: 230]
  { en: 'piano', ru: 'пианино' }, // [cite: 231]
  { en: 'picture', ru: 'картинка' }, // [cite: 232]
  { en: 'play', ru: 'играть' }, // [cite: 233]
  { en: 'radio', ru: 'радио' }, // [cite: 234]
  { en: 'read', ru: 'читать' }, // [cite: 235]
  { en: 'ride', ru: 'ездить верхом / кататься' }, // [cite: 236]
  { en: 'run', ru: 'бегать' }, // [cite: 237]
  { en: 'sing', ru: 'петь' }, // [cite: 238]
  { en: 'song', ru: 'песня' }, // [cite: 239]
  { en: 'sport', ru: 'спорт' }, // [cite: 240]
  { en: 'story', ru: 'история / рассказ' }, // [cite: 241]
  { en: 'swim', ru: 'плавать' }, // [cite: 242]
  { en: 'table tennis', ru: 'настольный теннис' }, // [cite: 243]
  { en: 'take a photo / picture', ru: 'сделать фото' }, // [cite: 244]
  { en: 'tennis', ru: 'теннис' }, // [cite: 245]
  { en: 'text', ru: 'текст / писать сообщение' }, // [cite: 246]
  { en: 'throw', ru: 'бросать' }, // [cite: 247]
  { en: 'toy', ru: 'игрушка' }, // [cite: 248]
  { en: 'walk', ru: 'идти / гулять' }, // [cite: 249]
  { en: 'watch', ru: 'смотреть' }, // [cite: 250]

  // Time
  { en: 'afternoon', ru: 'день / после полудня' }, // [cite: 252]
  { en: 'birthday', ru: 'день рождения' }, // [cite: 253]
  { en: 'clock', ru: 'часы (настенные)' }, // [cite: 254]
  { en: 'day', ru: 'день' }, // [cite: 255]
  { en: 'end', ru: 'конец' }, //
  { en: 'evening', ru: 'вечер' }, // [cite: 257]
  { en: 'morning', ru: 'утро' }, // [cite: 258]
  { en: 'night', ru: 'ночь' }, // [cite: 259]
  { en: 'today', ru: 'сегодня' }, // [cite: 260]
  { en: 'watch', ru: 'наручные часы' }, // [cite: 261]

  // Toys
  { en: 'ball', ru: 'мяч' }, // [cite: 263]
  { en: 'baseball', ru: 'бейсбол' }, // [cite: 264]
  { en: 'basketball', ru: 'баскетбол' }, // [cite: 265]
  { en: 'bike', ru: 'велосипед' }, // [cite: 266]
  { en: 'boat', ru: 'лодка' }, // [cite: 267]
  { en: 'car', ru: 'машина' }, // [cite: 268]
  { en: 'doll', ru: 'кукла' }, // [cite: 269]
  { en: 'game', ru: 'игра' }, // [cite: 270]
  { en: 'helicopter', ru: 'вертолет' }, // [cite: 271]
  { en: 'kite', ru: 'воздушный змей' }, // [cite: 272]
  { en: 'monster', ru: 'монстр' }, // [cite: 273]
  { en: 'plane', ru: 'самолет' }, // [cite: 274]
  { en: 'robot', ru: 'робот' }, // [cite: 275]
  { en: 'toy', ru: 'игрушка' }, // [cite: 276]
  { en: 'train', ru: 'поезд' }, // [cite: 277]
  { en: 'truck', ru: 'грузовик' }, // [cite: 278]

  // Transport
  { en: 'bus', ru: 'автобус' }, // [cite: 280]
  { en: 'drive', ru: 'водить' }, // [cite: 281]
  { en: 'fly', ru: 'летать' }, // [cite: 282]
  { en: 'go', ru: 'идти / ехать' }, // [cite: 283]
  { en: 'helicopter', ru: 'вертолет' }, // [cite: 284]
  { en: 'motorbike', ru: 'мотоцикл' }, // [cite: 285]
  { en: 'plane', ru: 'самолет' }, // [cite: 286]
  { en: 'ride', ru: 'ездить' }, // [cite: 287]
  { en: 'run', ru: 'бегать' }, // [cite: 288]
  { en: 'swim', ru: 'плавать' }, // [cite: 289]
  { en: 'train', ru: 'поезд' }, // [cite: 290]
];
// Делаем массив доступным глобально
window.preA1Vocabulary = preA1Vocabulary;

